/**
 * crest_map.js
 * Mapeamento de nomes de times da API para os arquivos locais de alta qualidade.
 */

window.CREST_MAP = {
  "uniclinic": "imgi_100_uniclinic.jpg",
  "gremio_pague_ce": "imgi_101_gremio_pague_ce.jpg",
  "ferroviario": "imgi_102_ferroviario.gif",
  "fluminense_pi": "imgi_103_fluminense_pi.png",
  "piaui": "imgi_104_piaui.png",
  "abc": "imgi_105_abc.jpg",
  "america": "imgi_106_america.png",
  "central_pe": "imgi_107_central_pe.png",
  "laguna_rn": "imgi_108_laguna_rn.jpg",
  "pe_maguary": "imgi_109_pe_maguary.png",
  "cruzeiro": "imgi_10_cruzeiro.png",
  "sousa_pb3": "imgi_110_sousa_pb3.png",
  "decisao_pe": "imgi_111_decisao_pe.png",
  "lagarto_se": "imgi_112_lagarto_se.png",
  "retro_pe": "imgi_113_retro_pe.png",
  "sergipe": "imgi_114_sergipe.png",
  "paraiba_pb": "imgi_115_paraiba_pb.png",
  "treze": "imgi_116_treze.jpg",
  "asa_al": "imgi_117_asa_al.png",
  "atletico_ba": "imgi_118_atletico_ba.png",
  "csa": "imgi_119_csa.png",
  "fla": "imgi_11_fla.png",
  "flamengo": "imgi_11_fla.png", // Alias comum
  "cse_al": "imgi_120_cse_al.png",
  "jacuipense_ba": "imgi_121_jacuipense_ba.jpg",
  "juazeirense_ba": "imgi_122_juazeirense_ba.png",
  "abecat_go": "imgi_123_abecat_go.png",
  "betim2_mg": "imgi_124_betim2_mg.png",
  "crac_go": "imgi_125_crac_go.png",
  "ivinhema_ms": "imgi_126_ivinhema_ms.gif",
  "operario_ms": "imgi_127_operario_ms.png",
  "uberlandia": "imgi_128_uberlandia.png",
  "democrata_gv": "imgi_129_democrata_gv.png",
  "fluminense": "imgi_12_fluminense.png",
  "porto_ba": "imgi_130_porto_ba.png",
  "real_noroeste_es": "imgi_131_real_noroeste_es.png",
  "riobranco": "imgi_132_riobranco.png",
  "tombense_mg": "imgi_133_tombense_mg.png",
  "vitoria_es": "imgi_134_vitoria_es.png",
  "agua_santa_sp": "imgi_135_agua_santa_sp.png",
  "america_rj": "imgi_136_america_rj.gif",
  "madureira": "imgi_137_madureira.jpg",
  "portuguesa_rj": "imgi_138_portuguesa_rj.png",
  "portuguesa": "imgi_139_portuguesa.png",
  "gremio": "imgi_13_gremio.png",
  "pouso_alegre_mg": "imgi_140_pouso_alegre_mg.png",
  "marica_rj": "imgi_141_marica_rj.png",
  "noroeste": "imgi_142_noroeste.png",
  "novaiguacu_rj": "imgi_143_novaiguacu_rj.jpg",
  "sampaio_correa_rj": "imgi_144_sampaio_correa_rj.png",
  "veloclube": "imgi_145_veloclube.png",
  "xv": "imgi_146_xv.png",
  "fc_cascavel_pr": "imgi_147_fc_cascavel_pr.png",
  "cianorte": "imgi_148_cianorte.jpg",
  "gbage_rs": "imgi_149_gbage_rs.jpg",
  "interrs": "imgi_14_interrs.png",
  "internacional": "imgi_14_interrs.png", // Alias comum
  "jec": "imgi_150_jec.gif",
  "santacatarina": "imgi_151_santacatarina.png",
  "saoluiz_rs": "imgi_152_saoluiz_rs.png",
  "azuriz_pr": "imgi_153_azuriz_pr.png",
  "blumenau_sc": "imgi_154_blumenau_sc.png",
  "gebrasil": "imgi_155_gebrasil.gif",
  "independente_pr": "imgi_156_independente_pr.png",
  "marcilio_dias_sc": "imgi_157_marcilio_dias_sc.png",
  "saojose_rs": "imgi_158_saojose_rs.png",
  "mirassol": "imgi_15_mirassol.jpg",
  "palmeiras": "imgi_16_palmeiras.png",
  "bragantino": "imgi_17_bragantino.png",
  "remo": "imgi_18_remo.png",
  "santos": "imgi_19_santos.png",
  "saopaulo": "imgi_20_saopaulo.png",
  "vasco": "imgi_21_vasco.png",
  "vitoria": "imgi_22_vitoria.png",
  "ammg": "imgi_23_ammg.png",
  "america_mg": "imgi_23_ammg.png", // Alias
  "aletico_del_rey_mg": "imgi_24_aletico_del_rey_mg.png",
  "atlego": "imgi_25_atlego.png",
  "atletico_go": "imgi_25_atlego.png", // Alias
  "avai": "imgi_26_avai.gif",
  "botasp": "imgi_27_botasp.png",
  "ceara": "imgi_28_ceara.png",
  "crb": "imgi_29_crb.gif",
  "cbf2": "imgi_2_cbf2.jpg",
  "criciuma": "imgi_30_criciuma.png",
  "cuiaba_mt": "imgi_31_cuiaba_mt.png",
  "cuiaba": "imgi_31_cuiaba_mt.png", // Alias
  "goias": "imgi_32_goias.png",
  "novorizontino_novo": "imgi_33_novorizontino_novo.jpg",
  "novorizontino": "imgi_33_novorizontino_novo.jpg", // Alias
  "fortaleza": "imgi_34_fortaleza.png",
  "juventude": "imgi_35_juventude.png",
  "londrina_pr": "imgi_36_londrina_pr.png",
  "londrina": "imgi_36_londrina_pr.png", // Alias
  "nautico": "imgi_37_nautico.png",
  "operario_pr": "imgi_38_operario_pr.png",
  "pontepreta": "imgi_39_pontepreta.gif",
  "atlpr": "imgi_3_atlpr.png",
  "athletico": "imgi_3_atlpr.png", // Alias
  "sao_bernarndo_sp": "imgi_40_sao_bernarndo_sp.png",
  "sport": "imgi_41_sport.gif",
  "vilanova": "imgi_42_vilanova.png",
  "amazonas_fc_am": "imgi_43_amazonas_fc_am.png",
  "anapolis": "imgi_44_anapolis.png",
  "barra_sc": "imgi_45_barra_sc.png",
  "botapb": "imgi_46_botapb.png",
  "brusque": "imgi_47_brusque.png",
  "caxias": "imgi_48_caxias.gif",
  "confianca_se": "imgi_49_confianca_se.png",
  "atletico": "imgi_4_atletico.png",
  "atletico_mg": "imgi_4_atletico.png", // Alias
  "ferroviaria": "imgi_50_ferroviaria.png",
  "figue": "imgi_51_figue.gif",
  "figueirense": "imgi_51_figue.gif", // Alias
  "floresta_ce": "imgi_52_floresta_ce.png",
  "guarani": "imgi_53_guarani.gif",
  "intl": "imgi_54_intl.png",
  "itabaiana": "imgi_55_itabaiana.gif",
  "ituano": "imgi_56_ituano.png",
  "maranhao": "imgi_57_maranhao.png",
  "gremio_maringa": "imgi_58_gremio_maringa.png",
  "paysandu_pa": "imgi_59_paysandu_pa.png",
  "paysandu": "imgi_59_paysandu_pa.png", // Alias
  "bahia": "imgi_5_bahia.png",
  "santacruz": "imgi_60_santacruz.png",
  "volta": "imgi_61_volta.png",
  "ypiranga_rs": "imgi_62_ypiranga_rs.png",
  "gas_rr": "imgi_63_gas_rr.png",
  "manauara_am": "imgi_64_manauara_am.png",
  "manaus_fc": "imgi_65_manaus_fc.png",
  "monteroraima_rr": "imgi_66_monteroraima_rr.png",
  "nacionalam": "imgi_67_nacionalam.png",
  "saoraimundo_rr": "imgi_68_saoraimundo_rr.jpg",
  "araguaina": "imgi_69_araguaina.jpg",
  "botafogo": "imgi_6_botafogo.gif",
  "galvez_ac": "imgi_70_galvez_ac.png",
  "guapore_ro": "imgi_71_guapore_ro.png",
  "humaita_ac": "imgi_72_humaita_ac.png",
  "independencia_ac": "imgi_73_independencia_ac.png",
  "porto_velho_ro": "imgi_74_porto_velho_ro.png",
  "aparecidense_go": "imgi_75_aparecidense_go.png",
  "brasiliense": "imgi_76_brasiliense.png",
  "gama": "imgi_77_gama.png",
  "inhumas_ec": "imgi_78_inhumas_ec.jpg",
  "uverdense_mt": "imgi_79_uverdense_mt.png",
  "chapeco": "imgi_7_chapeco.png",
  "chapecoense": "imgi_7_chapeco.png", // Alias
  "primavera_ac_mt": "imgi_80_primavera_ac_mt.jpg",
  "capital_df": "imgi_81_capital_df.png",
  "ceilandia_df": "imgi_82_ceilandia_df.jpg",
  "ceov_mt": "imgi_83_ceov_mt.jpg",
  "goiatuba": "imgi_84_goiatuba.png",
  "mixto": "imgi_85_mixto.gif",
  "rondonopolis": "imgi_86_rondonopolis.jpg",
  "aguia_pa": "imgi_87_aguia_pa.png",
  "imperatriz_ma": "imgi_88_imperatriz_ma.png",
  "oratorio_ap": "imgi_89_oratorio_ap.png",
  "corinthians": "imgi_8_corinthians.png",
  "tocantinopolis": "imgi_90_tocantinopolis.png",
  "trem_ap": "imgi_91_trem_ap.jpg",
  "tuna": "imgi_92_tuna.jpg",
  "iape_ma": "imgi_93_iape_ma.gif",
  "iguatu_ce": "imgi_94_iguatu_ce.png",
  "maracanau": "imgi_95_maracanau.png",
  "moto": "imgi_96_moto.jpg",
  "parnaiba_pi": "imgi_97_parnaiba_pi.png",
  "sampaio": "imgi_98_sampaio.png",
  "altos_pi": "imgi_99_altos_pi.png",
  "coritiba": "imgi_9_coritiba.png"
};
